### ISSUE TITLE
Merge similar terms for English/White people. Clarify ᎠᎩᎵᏏ is from the language and (Ꭰ)ᏲᏁᎦ is from the color (ᎤᏁᎦ).

### ISSUE THREAD

**Issue by CharlieMcVicker** [CherokeeLanguage/audio-lessons-generator-python#10]
There are some similar terms for English/White person/people that I think could be cleaned up.

I think these two terms could be merged, and the translation could be moved to just "A White person," since I frequently have heard speakers use this term for all sorts of White people, not just English folks.
https://github.com/CherokeeLanguage/audio-lessons-generator-python/blob/ba66935b23f5326dff05ef9eb87fdf02bc05ff5f/data/cll1-v3.txt#L30
https://github.com/CherokeeLanguage/audio-lessons-generator-python/blob/ba66935b23f5326dff05ef9eb87fdf02bc05ff5f/data/cll1-v3.txt#L243

Given that "English" person/people is given more semantically by:
https://github.com/CherokeeLanguage/audio-lessons-generator-python/blob/ba66935b23f5326dff05ef9eb87fdf02bc05ff5f/data/cll1-v3.txt#L239-L240

**Comment by michael-conrad** [comment]
Hrmmm

ᏴᏭᏁᎦ → ᏴᏫ + ᎤᏁᎦ. Person or people + white. Of the white people.

ᎠᏴᏭᏁᎦ → ᎠᏴᏫ + ᎤᏁᎦ. A single person + white.

Will have to think about better glosses for these two terms.

**Comment by michael-conrad** [comment]
This makes more sense to me:

```
yó:ne:ga; yó:ne:g; yv́:wúne:ga; yv́:wúne:g → English. Of the white peoples.

ayó:ne:ga; ayó:ne:g → An English or white person.
```

**Comment by CharlieMcVicker** [comment]
I think that definitely adds some clarity!
