### ISSUE TITLE
Clarify in English translation that this is a question

### ISSUE THREAD

**Issue by CharlieMcVicker** [CherokeeLanguage/audio-lessons-generator-python#2]
Hello again!

This term, which first shows up in Exercise 16 right now, is a little confusing. I think it would be better to have the English entry be a clear question, instead of just marked by inflection (in the male English TTS voice it is a little hard to tell that it is a question).

https://github.com/CherokeeLanguage/audio-lessons-generator-python/blob/1d38330a6d36518d56d6860fe59e46fad6a8d448/data/cll1-v3.txt#L293

**Comment by michael-conrad** [comment]
Yes. That is better. I'll upload replacement audio soon.
